# Generated by Django 5.1.7 on 2026-05-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_body_en_article_body_ru_article_body_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_uz',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary_uz',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
    ]
