# Generated by Django 5.1.7 on 2026-04-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_category_tag_article_category_article_tags'),
        ('articles', '0006_auto_20260421_1303'),
    ]

    operations = [
    ]
