# docker-compose.yml

version: '3.4'

services:
  db:
    image: mysql/mysql-server:8.0
    container_name: my-mysql-container-compose
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

  web: #<--- ONLY ONE 'web' service definition
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /c/Users/user-abdulloh/Documents/Github/personal_blog:/app # Corrected volume path
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 3306
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}

volumes:
  mysql_data:
    driver: local