# Generated by Django 5.1.7 on 2026-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('message', models.TextField(verbose_name='Your Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processed / Replied')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
